# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [pull_request, workflow_dispatch, push]
    

jobs:
  build:
        
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
                  
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: collectArtifacts
          
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            artifacts
